#include "actions.h"
#include "keymap.h"


// Implementation
const uint16_t PROGMEM fn_actions[] =
{
    [SYMBOL_ACTION] = ACTION_LAYER_MOMENTARY(SYMBOL_KEYMAP),
    [BRACK_AND_NUM_ACTION] = ACTION_LAYER_MOMENTARY(BRACKET_AND_NUMBER_KEYMAP),
    [NAV_ACTION] = ACTION_LAYER_MOMENTARY(NAVIGATION_KEYMAP),
    [FUNC_ACTION] = ACTION_LAYER_MOMENTARY(FUNCTION_KEYMAP),
    [HYPER_ACTION] = ACTION_LAYER_MOMENTARY(HYPER_KEYMAP),
    [EMOTICON_ACTION] = ACTION_LAYER_MOMENTARY(EMOTICON_KEYMAP)
};
